version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.1
    build:
      # context: https://github.com/puckel/docker-airflow.git#1.10.1
      context: https://github.com/pranavpawar3/docker-airflow.git
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        # PYTHON_DEPS: sqlalchemy==1.2.0, numpy==1.18.3, newspaper3k==0.2.8, requests==2.23.0, transformers==2.8.0, apache_airflow==1.10.10, pandas==0.25.3, pymongo==3.10.1, airflow==0.6 ,ipython==7.15.0, newspaper==0.1.0.7
        PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      # - ./examples/intro-example/dags:/usr/local/airflow/dags
      - ../2020_yali_dev/DEPLOY_QNA/pipeline_src:/usr/local/airflow/dags
      # - ../2020_yali_dev/DEPLOY_QNA/src:/usr/local/airflow/src
            
      ## create the base_models locally and download the models in this dir if you want 
      ## and if not present already, for correct mapping
      - ../2020_yali_dev/DEPLOY_QNA/base_models:/usr/local/airflow/base_models
      
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
      
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
